"""add off time fields to schedule

Revision ID: aa8686e46a99
Revises: d0dc9086cecb
Create Date: 2024-12-21 20:11:16.205091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa8686e46a99'
down_revision = 'd0dc9086cecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('off_start_time', sa.Time(), nullable=True))
    op.add_column('schedules', sa.Column('off_end_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'off_end_time')
    op.drop_column('schedules', 'off_start_time')
    # ### end Alembic commands ###
