"""add extra time fields to schedule

Revision ID: d0dc9086cecb
Revises: fe7f4b337a2b
Create Date: 2024-12-21 20:03:13.965027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0dc9086cecb'
down_revision = 'fe7f4b337a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('extra_start_time', sa.Time(), nullable=True))
    op.add_column('schedules', sa.Column('extra_end_time', sa.Time(), nullable=True))
    op.add_column('schedules', sa.Column('extra_slots', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'extra_slots')
    op.drop_column('schedules', 'extra_end_time')
    op.drop_column('schedules', 'extra_start_time')
    # ### end Alembic commands ###
